#SEARCH PARAMETERS: Varibles that can be modified for your search. Usually fine to leave as is
hmmer_eval: 0.001

#Allowable distance proteins of a system can be away from each other is length of system plus this buffer value
max_prot_buffer: 1 

#TREE PARAMETERS
#Taxonomic rank at which to resolve the tree. Options are: 'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'species'
final_rank: 'family'

#Minimum number of genomes in a taxon to be considered for final tree
min_final_rank_size: 10

#FILE PATHS: Locations of required databases. If running on SuperCloud should be ok to leave as is.

path_to_protein_db: $HOME/LaubLab_shared/nr_protein

path_to_taxa_file: $HOME/LaubLab_shared/assembly_summary.txt

path_to_ft: $HOME/LaubLab_shared/All_RefSeq_Assemblies_Accessions.parquet
